[package]
name = "pyzenoh_bridge"
version = "0.1.0"
edition = "2021"

[lib]
name = "pyzenoh_bridge"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.21.2", features = ["extension-module"] }
winapi = { version = "0.3", features = ["winerror"] }
numpy = "=0.21.0"
cdr = "0.2.4"
serde = "=1.0.225"
serde_derive = "1.0.225"
zenoh-ros-type = "=0.3.4"
zenoh = "=1.6.2"
zenoh-buffers = "=1.6.2"
zenoh-codec = "=1.6.2"
zenoh-collections = "=1.6.2"
zenoh-config = "=1.6.2"
zenoh-core = "=1.6.2"
zenoh-crypto = "=1.6.2"
zenoh-keyexpr = "=1.6.2"
zenoh-link = "=1.6.2"
zenoh-link-commons = "=1.6.2"
zenoh-link-quic = "=1.6.2"
zenoh-link-tcp = "=1.6.2"
zenoh-link-tls = "=1.6.2"
zenoh-link-udp = "=1.6.2"
zenoh-link-unixsock_stream = "=1.6.2"
zenoh-link-ws = "=1.6.2"
zenoh-macros = "=1.6.2"
zenoh-plugin-trait = "=1.6.2"
zenoh-protocol = "=1.6.2"
zenoh-result = "=1.6.2"
zenoh-runtime = "=1.6.2"
zenoh-sync = "=1.6.2"
zenoh-task = "=1.6.2"
zenoh-transport = "=1.6.2"
zenoh-util = "=1.6.2"